name: Build and Run all tests

# We use action's triggers 'push' and 'pull_request'.
# The strategy is the following: this action will be
# triggered on any push to 'main' branch and any pull
# request to any branch. Thus we avoid duplicate work-
# flows.
on:
  push:
    branches:
      - "main"
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: "macos-latest"
            # The MacOS runner doesn't have Docker installed, os can't run
            # `dazel`. Fall back to `bazel` instead.
            bazel-command: "bazel"
            bazel-config: ""
          - os: "ubuntu-latest"
            bazel-command: "dazel"
            bazel-config: "--config=asan"

    env:
      BAZEL_CONFIG: ${{ matrix.bazel-config }}

    defaults:
      run:
        shell: bash

    steps:
      # Checkout the repository under $GITHUB_WORKSPACE.
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"

      # Install Dazel, so that we use the same build tooling in our Actions as
      # we do on our workstations.
      - name: Install Dazel
        run: sudo pip3 install dazel

      - name: Build
        run: |
          ${{ matrix.bazel-command }} build \
            ${{ matrix.bazel-config }} \
            --spawn_strategy=local \
            -c dbg \
            --strip="never" \
            :grpc

      - name: Test
        run: |
          ${{ matrix.bazel-command }} test \
            ${{ matrix.bazel-config }} \
            --spawn_strategy=local \
            -c dbg \
            --strip="never" \
            --test_output=errors \
            test:grpc \
            --test_arg=--gtest_shuffle \
            --test_arg=--gtest_repeat=100

      - name: Debug using tmate (if failure)
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3
